[package]
name = "tracing-etw"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
tracing = {version = "0.1", default-features = false, features = ["std"]}
tracing-subscriber = {version="0.3", default-features = false, features=["std", "fmt", "registry"]}
tracelogging = ">= 1.1.0"
tracelogging_dynamic = ">= 1.1.0"
eventheader = "0.2"
eventheader_dynamic = "0.2"
lazy_static = "1.4"
crossbeam-utils = "0.8"
chrono = {version="0.4", default-features = false, features=["std"]}
smallvec = {version="1.10", default-features = false, features=["union", "const_generics"]}
arrayvec = {version="0.7", default-features = false}
