[package]
name = "tracing-etw"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
tracing = "0.1"
tracing-subscriber = {version="0.3", default-features = false, features=["std", "fmt", "registry"]}
tracelogging = ">= 1.1.0"
tracelogging_dynamic = ">= 1.1.0"
eventheader = "0.2"
eventheader_dynamic = "0.2"
lazy_static = "1.4"
crossbeam-utils = "0.8"
